# Generated by Django 2.2.6 on 2019-10-04 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesssoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processo.Departamento')),
                ('interessados', models.ManyToManyField(related_name='Interessados', to='processo.Pessoa')),
                ('investigados', models.ManyToManyField(related_name='Investigados', to='processo.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo.Pessoa')),
                ('matricula', models.CharField(max_length=15)),
            ],
            bases=('processo.pessoa',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo.Documento')),
                ('prazoAnterior', models.DateField()),
                ('prazoNovo', models.DateField()),
                ('justificativa', models.TextField()),
            ],
            bases=('processo.documento',),
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo.Documento')),
                ('instauracao', models.TextField()),
            ],
            bases=('processo.documento',),
        ),
        migrations.CreateModel(
            name='Tranmitacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSaida', models.DateField()),
                ('dataEntrada', models.DateField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepartamentoDestino', to='processo.Departamento')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepartamentoOrigem', to='processo.Departamento')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Usuario', to='processo.Funcionario'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processo.Documento')),
                ('dataEnvio', models.DateField()),
                ('departamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processo.Departamento')),
            ],
            bases=('processo.documento',),
        ),
        migrations.AddField(
            model_name='documento',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='processo.Funcionario'),
        ),
    ]
